export let palette = #{
	hex: #{
	    "black": "#000000",
	    "white": "#ffffff",
	    "neonGreen": "#04ff04",
	    "darkGreen": "048004ff",
	    "gray": "#505050",

	    "danger": "#f38ba8",
	},
	hexOpacity: #{
	    "black": "#000000ff",
	    "white": "#ffffffff",
	    "neonGreen": "#04ff04ff",
	    "darkGreen": "048004ff",
	    "gray": "#505050ff",

	    "danger": "#f38ba8ff",
	}
};

export let icon = #{
    light: "Papirus",
    dark: "Papirus-Dark"
};

export let font = "0xProto Nerd Font"
