# Print help
default:
    @just --list

# Build style.css file from style.scss
build:
	@sass style.scss style.css || { printf "\033[31m✘ Failed to build style.css\033[0m\n"; exit 1; }
	@printf "\033[32m✔ Successfully built style.css\033[0m\n"

# Reload waybar service
reload:
	@systemctl --user reload waybar.service || { printf "\033[31m✘ Failed to reload Waybar"; exit 1; }
	@printf "\033[32m✔ Waybar reloaded\033[0m\n"
